spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      schema: accounts
      maximum-pool-size: 5
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: none